source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EasyPostApi_Example', :exclusive => true do
  pod "EasyPostApi", :path => "../"
end

target 'EasyPostApi_Tests', :exclusive => true do
  pod "EasyPostApi", :path => "../"

  pod 'Quick', '~> 0.6.0'
  pod 'Nimble', '2.0.0-rc.3'
end
